" common
set nocompatible
set backupdir=$HOME/.vimbackup//
set directory=$HOME/.vimbackup//
set listchars=eol:¬
set list
set hidden
set incsearch
set ignorecase
set hlsearch
set cursorline
set foldmethod=indent
set shellpipe=>

" fn keys
let s:number=1
while s:number<13
  exe 'nmap <leader>'.s:number.' <F'.s:number.'>'
  let s:number+=1
endwhile

" pathogen
execute pathogen#infect()
Helptags

" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_map='<c-p>'
let g:ctrlp_cmd='CtrlP'
set wildignore+=*/target/*,*/node_modules/*
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$',
  \ 'file': '\.DS_Store$|\.ideal$|\.iml$'
  \ }
nnoremap <leader>p :CtrlPTag<cr>

" tagbar
nnoremap <leader>0 :TagbarToggle<CR>
set tags=./tags;
nnoremap <silent> <leader>gt :!ctags -R -f ./tags .<CR>
let g:tagbar_type_scala = {
  \ 'ctagstype' : 'Scala',
  \ 'kinds'     : [
    \ 'p:packages:1',
    \ 'V:values',
    \ 'v:variables',
    \ 'T:types',
    \ 't:traits',
    \ 'o:objects',
    \ 'a:aclasses',
    \ 'c:classes',
    \ 'r:cclasses',
    \ 'm:methods'
  \ ]
\ }
let g:tagbar_autofocus=1
let g:tagbar_autoclose=1
let g:tagbar_width=25
let g:tagbar_compact=1

" syntax
syntax on
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set bs=indent,eol,start
nnoremap J mzJ`z

" colorsheme
set background=dark
colorscheme monochrome

" marginline
highlight OverLength ctermfg=red
match OverLength /\%81v.\+/
set colorcolumn=81
hi ColorColumn ctermbg=233

" gutter
set number
set autoread
let g:gitgutter_realtime=1
let g:gitgutter_eager=1

" airline
set laststatus=2
let g:airline#extensions#tabline#enabled=1
let g:airline_theme='airlineish'
let g:airline_left_sep=''
let g:airline_right_sep=''

" search n replace
nnoremap <F3> :cn<CR>
nnoremap <F4> :cp<CR>
nnoremap zr :vimgrep <cword> **/*
nnoremap gr :vimgrep 
nnoremap zx :noh<CR>

" NERDTree
nnoremap <F2> :NERDTreeFind<CR>
let g:NERDTreeWinSize=50
let g:NERDTreeQuitOnOpen=1

" Easymotion
nmap s <Plug>(easymotion-s)
vmap s <Plug>(easymotion-s)
imap <leader>s <Plug>(easymotion-s)

" Ack.vim
let g:ack_autoclose = 1

" custom Keymap
nmap <Enter> o<esc>k
nnoremap <C-h> :bp<cr>
nnoremap <C-l> :bn<cr>
nnoremap <C-x> :bd<cr>

