" common
set nocompatible
set backupdir=$HOME/.vimbackup//
set directory=$HOME/.vimbackup//
set listchars=eol:¬
set list
set hidden
set incsearch
set ignorecase
set hlsearch
set cursorline

" pathogen
execute pathogen#infect()
Helptags

" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_map='<F12>'
let g:ctrlp_cmd='CtrlP'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$',
  \ 'file': '\.DS_Store$|\.ideal$|\.iml$'
  \ }
nnoremap <F11> :CtrlPTag<cr>

" tagbar
nnoremap <F8> :TagbarToggle<CR>
set tags=./tags;
nnoremap <silent> <F5> :!ctags -R -f ./tags .<CR>
let g:tagbar_type_scala = {
  \ 'ctagstype' : 'Scala',
  \ 'kinds'     : [
    \ 'p:packages:1',
    \ 'V:values',
    \ 'v:variables',
    \ 'T:types',
    \ 't:traits',
    \ 'o:objects',
    \ 'a:aclasses',
    \ 'c:classes',
    \ 'r:cclasses',
    \ 'm:methods'
  \ ]
\ }
let g:tagbar_autofocus=1
let g:tagbar_autoclose=1
let g:tagbar_width=25
let g:tagbar_compact=1

" syntax
syntax on
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set bs=indent,eol,start
nnoremap J mzJ`z

" colorsheme
set background=dark
colorscheme monochrome

" marginline
highlight OverLength ctermfg=red
match OverLength /\%81v.\+/
set colorcolumn=81
hi ColorColumn ctermbg=233

" gutter
set number
set autoread
let g:gitgutter_realtime=1
let g:gitgutter_eager=1

" airline
set laststatus=2
let g:airline#extensions#tabline#enabled=1
let g:airline_theme='airlineish'
let g:airline_left_sep=''
let g:airline_right_sep=''

" easygrep
let g:EasyGrepCommand=0
let g:EasyGrepFilesToExclude=".git,.iml,.DS_Store,.iml"
nnoremap <F10> :GrepOptions<CR>
set wildignore+=.git,.git/**,.idea,.idea/**,.DS_Store,/.iml,*.class,**/target/**

" NERDTree
nnoremap <F2> :NERDTreeTabsToggle<CR>
let g:NERDTreeQuitOnOpen=1

