" common
set nocompatible
set backupdir=$HOME/.vimbackup//
set directory=$HOME/.vimbackup//
set listchars=eol:¬
set list
set hidden
set incsearch
set hlsearch

" pathogen
execute pathogen#infect()
Helptags

" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_map='<c-p>'
let g:ctrlp_cmd='CtrlP'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$',
  \ 'file': '\.DS_Store$|\.ideal$|\.iml$'
  \ }
nnoremap <leader>. :CtrlPTag<cr>

" tagbar
nnoremap <leader>b :TagbarToggle<CR>
set tags=./tags;
map <F6> :!ctags -Ra -f ./tags .<CR>
map <F5> :!ctags -R -f ./tags .<CR>

" syntax
syntax on
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set bs=indent,eol,start
nnoremap J mzJ`z

" colorsheme
set background=dark
colorscheme monochrome

" marginline
highlight OverLength ctermfg=red
match OverLength /\%81v.\+/
set colorcolumn=81
hi ColorColumn ctermbg=233

" gutter
set number
set autoread
let g:gitgutter_realtime=1
let g:gitgutter_eager=1

" airline
set laststatus=2
let g:airline#extensions#tabline#enabled=1
let g:airline_theme='airlineish'
let g:airline_left_sep=''
let g:airline_right_sep=''

" easygrep
let g:EasyGrepCommand=0
let g:EasyGrepFilesToExclude=".git,.iml,.DS_Store,.iml"
map <leader> vo GrepOptions
set wildignore+=.git,.git/**,.idea,.idea/**,.DS_Store,/.iml,*.class,**/target/**

